name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_SECRET: "https://fake.com"
  NEXTAUTH_URL: "https://fake.com"
  GOOGLE_CLIENT_ID: "https://fake.com"
  GOOGLE_CLIENT_SECRET: "https://fake.com"
  NEXT_PUBLIC_GOOGLE_MAP_KEY: "https://fake.com"
  S3_UPLOAD_KEY: "https://fake.com"
  S3_UPLOAD_SECRET: "https://fake.com"
  S3_UPLOAD_BUCKET: "https://fake.com"
  S3_UPLOAD_REGION: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Print Environment Variable
        run: echo $DATABASE_URL
